bundler_args: --without development --path=~/.bundle
sudo: false
language: ruby
rvm:
 - "2.3.0"
cache:
  bundle: true
  directories:
  - ~/.bundle
  - react-webclient/node_modules
env:
 - RAILS_DATABASE_USER=postgres
addons:
  postgresql: '9.4'
services:
  - postgresql
script:
  - cd rails-api && bundle exec rake
  - cd ..
  - cd react-webclient && npm run test
  - npm run build
  - cd ..
  - cp -r react-webclient/static/* rails-api/public
  - cp -r react-webclient/build/* rails-api/public
  - cd rails-api && bundle exec rspec spec/features
branches:
  only:
  - master
before_install:
  - export DISPLAY=:99.0
  - export CHROME_BIN=chromium-browser
  - export CHROME_DRIVER=$(pwd)/chromedriver
  - export API_URL='http://localhost:3388'
  - sh -e /etc/init.d/xvfb start
  - wget https://chromedriver.storage.googleapis.com/2.20/chromedriver_linux64.zip
  - unzip -qq chromedriver_linux64.zip
  - nvm install 4.1
  - cd rails-api && bundle && bundle exec rake db:setup
  - cd ../react-webclient && npm install
  - cd ..
