language: ruby
rvm:
 - "2.2.1"

cache:
  bundler: true

env:
 - SECRET_KEY_BASE=c8d3918e9944a5b22 RAILS_DATABASE_USER=postgres

services:
  - postgresql

script:
  - bundle exec rake db:setup
  - bundle exec rake

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - wget https://chromedriver.storage.googleapis.com/2.19/chromedriver_linux64.zip
  - unzip -qq chromedriver_linux64.zip
  - export PATH=$PATH:$PWD
