language: ruby
rvm:
 - "2.2.1"

cache:
  bundler: true

env:
 - SECRET_KEY_BASE=c8d3918e9944a5b22 RAILS_DATABASE_USER=postgres

services:
  - postgresql

script:
  - bundle exec rake db:setup --trace
  - bundle exec rake

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - wget -O ~/chromedriver.zip https://chromedriver.storage.googleapis.com/2.20/chromedriver_linux64.zip && unzip ~/chromedriver.zip chromedriver && mv ~/chromedriver /usr/local/bin/
  - export PATH=$PATH:/usr/local/bin/
