sudo: required
dist: trusty
language: ruby
node_js:
  - "4.1"
rvm:
 - "2.3.0"
cache:
  bundler: true
  directories:
  - node_modules
env:
 - SECRET_KEY_BASE=c8d3918e9944a5b22 RAILS_DATABASE_USER=postgres CHROME_BIN=chromium-browser
addons:
  postgresql: '9.4'
services:
  - postgresql
script:
  - npm install
  - npm run ci
  - bundle exec rake db:setup
  - bundle exec rake
before_install:
  - nvm install 4.1
  - export CHROME_DRIVER=$(pwd)/chromedriver
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - wget https://chromedriver.storage.googleapis.com/2.12/chromedriver_linux64.zip
  - unzip -qq chromedriver_linux64.zip
branches:
  only:
  - master