sudo: false
language: ruby
rvm:
 - "2.3.0"
cache:
  bundler: true
  directories:
  - react-webclient/node_modules
env:
 - RAILS_DATABASE_USER=postgres
addons:
  postgresql: '9.4'
services:
  - postgresql
script:
  - cd rails-api && bundle exec rake
  - cd ..
  - cd react-webclient && npm run ci
branches:
  only:
  - master
before_install:
  - export DISPLAY=:99.0
  - export CHROME_BIN=chromium-browser
  - sh -e /etc/init.d/xvfb start
  - wget https://chromedriver.storage.googleapis.com/2.20/chromedriver_linux64.zip
  - unzip -qq chromedriver_linux64.zip
  - export CHROME_DRIVER=$(pwd)/chromedriver
  - nvm install 4.1
  - cd rails-api && bundle && bundle exec rake db:setup
  - cd ../react-webclient && npm install
  - cd ..
