source 'https://rubygems.org'
ruby '2.1.1'

gem 'dotenv-rails'
gem 'rails', '4.1.9'
gem 'mina'
gem 'pg'
gem 'devise'
gem 'sass-rails', '~> 4.0.0'
gem 'foundation-rails'
gem 'foundation-icons-sass-rails'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 1.2'
gem 'exception_notification'
gem 'dynamic_form'
gem 'bcrypt', '~> 3.1.2'
gem 'passenger'
gem 'nested_form'

group :development, :test do
  gem 'awesome_print'
  gem 'bullet'
  gem 'factory_girl'
  gem 'rspec-rails', '2.13.1'
  gem 'shoulda-matchers'
  gem 'selenium-webdriver', '~> 2.35.1'
  gem 'capybara', '2.1.0'
  gem 'guard-rspec', '2.5.0'
  gem 'growl', '1.0.3'
  gem 'terminal-notifier-guard'
end
