source 'https://rubygems.org'
ruby '2.1.1'

gem 'dotenv-rails'
gem 'rails', '4.2.0'
gem 'mina'
gem 'pg'
gem 'devise'
gem 'sass-rails', '~> 5.0.0'
gem 'foundation-rails'
gem 'foundation-icons-sass-rails'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 1.2'
gem 'exception_notification'
gem 'dynamic_form'
gem 'bcrypt', '~> 3.1.2'
gem 'passenger'
gem 'nested_form'
gem 'react-rails', '~> 1.0'
gem 'puma'

group :development, :test do
  gem 'faker'
  gem 'awesome_print'
  gem 'bullet'
  gem 'factory_girl_rails'
  gem 'rspec-rails', '~> 3.0'
  gem 'shoulda-matchers'
  gem 'capybara'
  gem 'byebug'
end
