source 'https://rubygems.org'
gem 'dotenv-rails'

gem 'rails', '4.2.5'

gem 'bcrypt', '~> 3.1.2'
gem 'coffee-rails', '~> 4.0.0'
gem 'devise'
gem 'exception_notification'
gem 'foundation-icons-sass-rails'
gem 'foundation-rails'
gem 'jbuilder', '~> 1.2'
gem 'jquery-rails'
gem 'mina'
gem 'passenger'
gem 'pg'
gem 'react_webpack_rails', '~> 0.0.5'
gem 'sass-rails', '~> 5.0.0'
gem 'uglifier', '>= 1.3.0'

group :development, :test do
  gem 'awesome_print'
  gem 'bullet'
  gem 'capybara'
  gem 'database_cleaner'
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'pry'
  gem 'puma'
  gem 'rspec-rails', '~> 3.0'
  gem 'selenium-webdriver'
  gem 'shoulda-matchers'
end
