// Annual Budgets
export const ANNUAL_BUDGET_UPDATED = 'ANNUAL_BUDGET_UPDATED'
export const ANNUAL_BUDGET_DATE_UPDATED = 'ANNUAL_BUDGET_DATE_UPDATED'
export const ANNUAL_BUDGET_ITEM_ADDED = 'ANNUAL_BUDGET_ITEM_ADDED'
export const ANNUAL_BUDGET_ITEM_UPDATED = 'ANNUAL_BUDGET_ITEM_UPDATED'
export const ANNUAL_BUDGET_ITEM_DELETED = 'ANNUAL_BUDGET_ITEM_DELETED'
