// Annual Budgets
export const ANNUAL_BUDGET_UPDATED = 'ANNUAL_BUDGET_UPDATED'
export const ANNUAL_BUDGET_DATE_UPDATED = 'ANNUAL_BUDGET_DATE_UPDATED'
export const ANNUAL_BUDGET_ITEM_ADDED = 'ANNUAL_BUDGET_ITEM_ADDED'
export const ANNUAL_BUDGET_ITEM_UPDATED = 'ANNUAL_BUDGET_ITEM_UPDATED'
export const ANNUAL_BUDGET_ITEM_DELETED = 'ANNUAL_BUDGET_ITEM_DELETED'

// Budgets
export const BUDGET_UPDATED = 'BUDGET_UPDATED'
export const BUDGET_CATEGORY_UPDATED = 'BUDGET_CATEGORY_UPDATED'
export const BUDGET_DATE_UPDATED = 'BUDGET_DATE_UPDATED'
// Items
export const BUDGET_ITEM_ADDED = 'BUDGET_ITEM_ADDED'
export const BUDGET_ITEM_UPDATED = 'BUDGET_ITEM_UPDATED'
export const BUDGET_ITEM_DELETED = 'BUDGET_ITEM_DELETED'
// Expenses
export const BUDGET_ITEM_EXPENSE_ADDED = 'BUDGET_ITEM_EXPENSE_ADDED'
export const BUDGET_ITEM_EXPENSE_UPDATED = 'BUDGET_ITEM_EXPENSE_UPDATED'
export const BUDGET_ITEM_EXPENSE_DELETED = 'BUDGET_ITEM_EXPENSE_DELETED'

// Navigation
export const NAVIGATE = 'NAVIGATE'
export const NAV_PUSH = 'NAV_PUSH'
export const NAV_POP = 'NAV_POP'
export const NAV_JUMP_TO_KEY = 'NAV_JUMP_TO_KEY'
export const NAV_JUMP_TO_INDEX = 'NAV_JUMP_TO_INDEX'
export const NAV_RESET = 'NAV_RESET'
export const NAV_REPLACE_AT_INDEX = 'NAV_REPLACE_AT_INDEX'

// Sessions
export const SESSION_UPDATED = 'SESSION_UPDATED'

// Account
export const ACCOUNT_PHOTO_UPDATED = 'ACCOUNT_PHOTO_UPDATED'
export const ACCOUNT_USER_UPDATED = 'ACCOUNT_USER_UPDATED'

// Statistics
export const STAT_BUDGET_UPDATED = 'STAT_BUDGET_UPDATED'
export const STAT_BUDGET_DATE_UPDATED = 'STAT_BUDGET_DATE_UPDATED'

// Detailed Budgets
export const DETAILED_BUDGET_UPDATED = 'DETAILED_BUDGET_UPDATED'
export const DETAILED_BUDGET_CATEGORY_UPDATED = 'DETAILED_BUDGET_CATEGORY_UPDATED'
export const DETAILED_BUDGET_DATE_UPDATED = 'DETAILED_BUDGET_DATE_UPDATED'
// Detailed Budget Items
export const DETAILED_BUDGET_ITEM_ADDED = 'DETAILED_BUDGET_ITEM_ADDED'
export const DETAILED_BUDGET_ITEM_UPDATED = 'DETAILED_BUDGET_ITEM_UPDATED'
export const DETAILED_BUDGET_ITEM_DELETED = 'DETAILED_BUDGET_ITEM_DELETED'
