sudo: false
language: node_js
node_js:
  - "4.1"
cache:
  directories:
  - node_modules
before_install:
  - export DISPLAY=:99.0
  - export CHROME_BIN=chromium-browser
  - sh -e /etc/init.d/xvfb start
branches:
  only:
  - master