sudo: false
language: ruby
rvm:
 - "2.3.0"
cache:
  bundler: true
env:
 - RAILS_DATABASE_USER=postgres
addons:
  postgresql: '9.4'
services:
  - postgresql
script:
  - bundle exec rake db:setup
  - bundle exec rake
branches:
  only:
  - master