source 'https://rubygems.org'

ruby '2.4.1'

gem 'devise',    '~> 4.2'
gem 'jbuilder',  '~> 2.5'
gem 'mina',      '~> 1.0'
gem 'paperclip', '~> 5.0'
gem 'pg',        '~> 0.21'
gem 'rack-cors', '~> 0.4.0'
gem 'rails',     '~> 5.1'
gem 'rollbar',   '~> 2.14'

group :development, :test, :mobile_integration do
  gem 'bullet'
  gem 'capybara'
  gem 'database_cleaner'
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'pry'
  gem 'puma'
  gem 'rspec-rails', '~> 3.5'
  gem 'selenium-webdriver'
end
