source 'https://rubygems.org'

gem 'devise',    '~> 4.1'
gem 'jbuilder',  '~> 2.5'
gem 'paperclip', '~> 5.0'
gem 'pg',        '~> 0.18'
gem 'rack-cors', '~> 0.4.0'
gem 'rails',     '4.2.5'

group :development, :test, :mobile_integration do
  gem 'awesome_print'
  gem 'bullet'
  gem 'capybara'
  gem 'database_cleaner'
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'pry'
  gem 'puma'
  gem 'rspec-rails', '~> 3.0'
  gem 'selenium-webdriver'
  gem 'shoulda-matchers'
end
